import type { StockAssetConfig } from '../types/stocks.ts';

export const WATCHED_STOCKS: StockAssetConfig[] = [
  {
    symbol: 'SPY',
    name: 'SPDR S&P 500 ETF Trust',
    category: 'INDEX',
    sector: 'Broad Market ETF',
    description: '美股标普 500 核心基准指数，涵盖美国最大 500 家上市公司，大盘配置基石。',
    maxPortfolioCapPct: 0.35,
    baseWeightPct: 0.25,
    ttmPe: 27.2,
    forwardPe: 22.4,
    pegRatio: 1.8,
    fcfYieldPct: 3.4,
    buybackYieldPct: 2.1,
    sbcDilutionRatePct: 0.4,
    grossMarginPct: 35.0,
    revenueGrowthYoY: 5.8,
  },
  {
    symbol: 'QQQ',
    name: 'Invesco QQQ Trust (Nasdaq 100)',
    category: 'INDEX',
    sector: 'Tech Index ETF',
    description: '纳斯达克 100 科技核心龙头指数，重仓全球最优质科技与 AI 基础设施平台。',
    maxPortfolioCapPct: 0.30,
    baseWeightPct: 0.20,
    ttmPe: 31.5,
    forwardPe: 25.8,
    pegRatio: 1.9,
    fcfYieldPct: 3.2,
    buybackYieldPct: 2.3,
    sbcDilutionRatePct: 0.6,
    grossMarginPct: 48.0,
    revenueGrowthYoY: 10.2,
  },
  {
    symbol: 'NVDA',
    name: 'NVIDIA Corporation',
    category: 'TECH_GROWTH',
    sector: 'Semiconductors & AI',
    description: '全球 AI 算力与 GPU 生态唯一垄断者，净利润率超过 50%，拥有巨额现金流与股票回购。',
    maxPortfolioCapPct: 0.12,
    baseWeightPct: 0.08,
    ttmPe: 44.8,
    forwardPe: 31.2,
    pegRatio: 1.1,
    fcfYieldPct: 2.8,
    buybackYieldPct: 1.8,
    sbcDilutionRatePct: 0.7,
    grossMarginPct: 75.1,
    revenueGrowthYoY: 94.0,
  },
  {
    symbol: 'AAPL',
    name: 'Apple Inc.',
    category: 'TECH_GROWTH',
    sector: 'Consumer Tech & Hardware',
    description: '全球股东回报之王，年均投入约 1000 亿美元回购注销股本，十年销毁超 35% 总股数。',
    maxPortfolioCapPct: 0.12,
    baseWeightPct: 0.08,
    ttmPe: 33.4,
    forwardPe: 27.5,
    pegRatio: 2.4,
    fcfYieldPct: 3.8,
    buybackYieldPct: 3.5,
    sbcDilutionRatePct: 0.8,
    grossMarginPct: 46.2,
    revenueGrowthYoY: 6.1,
  },
  {
    symbol: 'MSFT',
    name: 'Microsoft Corporation',
    category: 'TECH_GROWTH',
    sector: 'Cloud & Enterprise AI',
    description: '企业云服务与生成式 AI 落地领跑者，高壁垒订阅制 SaaS，自由现金流充沛且稳步回购。',
    maxPortfolioCapPct: 0.12,
    baseWeightPct: 0.08,
    ttmPe: 33.8,
    forwardPe: 28.0,
    pegRatio: 2.1,
    fcfYieldPct: 2.7,
    buybackYieldPct: 1.2,
    sbcDilutionRatePct: 0.6,
    grossMarginPct: 69.8,
    revenueGrowthYoY: 15.2,
  },
  {
    symbol: 'GOOGL',
    name: 'Alphabet Inc.',
    category: 'TECH_GROWTH',
    sector: 'Search, Cloud & AI',
    description: '搜索与全球数据护城河，YouTube 与 GCP 持续强劲，历史估值处于科技巨头最低分位数之一。',
    maxPortfolioCapPct: 0.12,
    baseWeightPct: 0.08,
    ttmPe: 22.5,
    forwardPe: 18.9,
    pegRatio: 1.2,
    fcfYieldPct: 4.5,
    buybackYieldPct: 3.2,
    sbcDilutionRatePct: 1.1,
    grossMarginPct: 57.5,
    revenueGrowthYoY: 14.1,
  },
  {
    symbol: 'MSTR',
    name: 'MicroStrategy Inc.',
    category: 'CRYPTO_PROXY',
    sector: 'Bitcoin Treasury Proxy',
    description: '华尔街杠杆化比特币储备载体，通过低息可转债持续发行增持 BTC，高贝塔弹性标的。',
    maxPortfolioCapPct: 0.05,
    baseWeightPct: 0.03,
    ttmPe: 85.0,
    forwardPe: 65.0,
    pegRatio: 4.5,
    fcfYieldPct: -0.5,
    buybackYieldPct: 0.0,
    sbcDilutionRatePct: 2.5,
    grossMarginPct: 72.0,
    revenueGrowthYoY: -2.3,
  },
  {
    symbol: 'COIN',
    name: 'Coinbase Global Inc.',
    category: 'CRYPTO_PROXY',
    sector: 'Crypto Infrastructure',
    description: '美国唯一合规加密第一股，Base 链生态繁荣与稳定币 USDC 利息收益构成第二增长曲线。',
    maxPortfolioCapPct: 0.05,
    baseWeightPct: 0.03,
    ttmPe: 38.0,
    forwardPe: 29.5,
    pegRatio: 1.6,
    fcfYieldPct: 3.1,
    buybackYieldPct: 1.0,
    sbcDilutionRatePct: 2.2,
    grossMarginPct: 84.5,
    revenueGrowthYoY: 78.5,
  },
];

export function getWatchedStocks(): StockAssetConfig[] {
  return WATCHED_STOCKS;
}
